name: learn_english
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0
  flip_card: ^0.4.4
  cupertino_icons: ^1.0.0
  flutter_tts: ^2.0.0
  firebase_analytics: ^6.3.0
  firebase_admob: ^0.10.3
  curved_navigation_bar: ^0.3.7
  lottie: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/confetti.json
    - assets/lottie/lazy.json

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf